/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 3DCart.glb --transform 
Files: 3DCart.glb [3.03MB] > /Users/mehdi/Documents/dev/portfolio/public/3DCart-transformed.glb [342.42KB] (89%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

type GroupProps = React.ComponentProps<"group">;
interface ModelProps extends GroupProps {
  disableMobileScaling?: boolean;
  modelRef?: React.Ref<THREE.Group>;
}

export const Model = ({ modelRef, ...props }: ModelProps) => {
  const { nodes } = useGLTF("/3DCart-transformed.glb") as unknown as {
    nodes: { LOGO: THREE.Mesh };
    materials: { [key: string]: THREE.Material };
  };

  return (
    <group ref={modelRef} {...props} dispose={null}>
      <mesh
        geometry={nodes.LOGO.geometry}
        material={nodes.LOGO.material}
        position={[0.035, 0.223, -4.893]}
        rotation={[-Math.PI / 2, Math.PI / 4, -Math.PI]}
        scale={0.01}
      />
    </group>
  );
};

useGLTF.preload("/3DCart-transformed.glb");
export default Model;
