/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Cart_portfolio.glb --transform 
Files: Cart_portfolio.glb [283.74MB] > /Users/mehdi/Documents/dev/portfolio/public/Cart_portfolio-transformed.glb [21.62MB] (92%)
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
type GroupProps = React.ComponentProps<"group">;
interface ModelProps extends GroupProps {
  disableMobileScaling?: boolean;
  modelRef?: React.Ref<THREE.Group>;
}

import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    LOGO: THREE.Mesh;
    Extrude004: THREE.Mesh;
    LeSchrift004: THREE.Mesh;
    tire004: THREE.Mesh;
    Cylinder: THREE.Mesh;
    Plane: THREE.Mesh;
    body: THREE.Mesh;
    steer_1: THREE.Mesh;
    Cylinder_1: THREE.Mesh;
    Cube_2: THREE.Mesh;
    Sweep_12: THREE.Mesh;
    Cylinder_1_4: THREE.Mesh;
    Plane_3: THREE.Mesh;
    Plane_2_2: THREE.Mesh;
    Plane_1_3: THREE.Mesh;
  };
  materials: {
    Gold: THREE.Material;
    ["Brushed Aluminum Black Stained"]: THREE.Material;
    ["White leather"]: THREE.Material;
    ["Tyre Sidewall"]: THREE.Material;
    ["Plastic purple red material"]: THREE.Material;
    ["Metal floor"]: THREE.Material;
    ["Black matte metal"]: THREE.Material;
    Carbon: THREE.Material;
    ["Dark metal"]: THREE.Material;
    ["Scratched black metal"]: THREE.Material;
    ["Plastic 3"]: THREE.Material;
    ["Patterned metal"]: THREE.Material;
    ["Leather Fabric - Black 70"]: THREE.Material;
    ["SciFi Structural Panelling.006"]: THREE.Material;
  };
};

export const Model = ({ modelRef, ...props }: ModelProps) => {
  const { nodes, materials } = useGLTF(
    "/Cart_portfolio-transformed.glb"
  ) as unknown as GLTFResult;
  return (
    <group ref={modelRef} {...props} dispose={null} position={[0, 0, 0.5]}>
      <mesh
        geometry={nodes.LOGO.geometry}
        material={materials.Gold}
        position={[0.035, 0.223, -4.893]}
        rotation={[-Math.PI / 2, Math.PI / 4, -Math.PI]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Extrude004.geometry}
        material={materials["Brushed Aluminum Black Stained"]}
        position={[3.098, 0.302, 3.47]}
        rotation={[Math.PI / 2, 0, -1.244]}
        scale={0.034}
      />
      <mesh
        geometry={nodes.LeSchrift004.geometry}
        material={materials["White leather"]}
        position={[3.553, 0.24, 3.427]}
        rotation={[Math.PI / 2, 0, -1.244]}
        scale={0.034}
      />
      <mesh
        geometry={nodes.tire004.geometry}
        material={materials["Tyre Sidewall"]}
        position={[3.087, 0.316, 3.442]}
        rotation={[Math.PI / 2, 0, -1.244]}
        scale={0.034}
      />
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials["Plastic purple red material"]}
        position={[0.616, 0.333, -3.499]}
        rotation={[-1.075, 0, Math.PI]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials["Metal floor"]}
        position={[0.617, 0.223, -3.424]}
        rotation={[-Math.PI / 2, -1.571, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.body.geometry}
        material={materials["Black matte metal"]}
        position={[0.043, 0.08, -0.114]}
        rotation={[1.571, 0.017, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.steer_1.geometry}
        material={nodes.steer_1.material}
        position={[-0.003, 0.308, -2.01]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Cylinder_1.geometry}
        material={materials.Carbon}
        position={[-0.033, 0.938, 2.134]}
        rotation={[0, -0.01, Math.PI / 2]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Cube_2.geometry}
        material={materials["Dark metal"]}
        position={[-0.691, 1.67, 2.14]}
        rotation={[-Math.PI / 2, -0.698, -Math.PI]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Sweep_12.geometry}
        material={materials["Scratched black metal"]}
        position={[-0.168, 1.88, 2.142]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Cylinder_1_4.geometry}
        material={materials["Plastic 3"]}
        position={[-1.606, 0.176, -3.506]}
        rotation={[Math.PI / 2, -0.837, Math.PI]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Plane_3.geometry}
        material={materials["Patterned metal"]}
        position={[0.023, 2.468, -3.194]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.009}
      />
      <mesh
        geometry={nodes.Plane_2_2.geometry}
        material={materials["Leather Fabric - Black 70"]}
        position={[1.34, 0.666, -0.765]}
        rotation={[1.828, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Plane_1_3.geometry}
        material={materials["SciFi Structural Panelling.006"]}
        position={[-2.229, 3.939, -0.257]}
        rotation={[Math.PI / 2, Math.PI / 2, 0]}
        scale={0.01}
      />
    </group>
  );
};

useGLTF.preload("/Cart_portfolio-transformed.glb");
export default Model;
