/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 LegacyLines.glb --transform 
Files: LegacyLines.glb [891.5KB] > D:\Dokumente\Mehdi Studium Informatik und Design\7. Semester\Bachelor\my-portfolio-proj\public\LegacyLines-transformed.glb [80.04KB] (91%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

type GroupProps = React.ComponentProps<"group">;
interface ModelProps extends GroupProps {}

// eslint-disable-next-line react/display-name
export const Model = ({
  ref,
  ...props
}: ModelProps & {
  ref: React.RefObject<THREE.Group>;
}) => {
  const { nodes, materials } = useGLTF(
    "/LegacyLines1-transformed.glb"
  ) as unknown as {
    nodes: { [key: string]: THREE.Mesh };
    materials: { [key: string]: THREE.Material };
  };
  return (
    <group {...props} dispose={null} ref={ref}>
      <group
        position={[0, 1.5, 0]}
        rotation={[1.554, -0.102, 3.114]}
        scale={105.456}
      >
        <mesh
          geometry={nodes.Curve131.geometry}
          material={materials["SVGMat.056"]}
        />
        <mesh
          geometry={nodes.Curve131_1.geometry}
          material={materials["SVGMat.058"]}
        />
        <mesh
          geometry={nodes.Curve131_2.geometry}
          material={materials["SVGMat.068"]}
        />
      </group>
    </group>
  );
};
useGLTF.preload("/LegacyLines1-transformed.glb");
export default Model;
