/* eslint-disable react/display-name */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 WotW_title_3D.glb --transform 
Files: WotW_title_3D.glb [1.35MB] > D:\Dokumente\Mehdi Studium Informatik und Design\7. Semester\Bachelor\my-portfolio-proj\public\WotW_title_3D-transformed.glb [89.04KB] (93%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

type GroupProps = JSX.IntrinsicElements["group"];
interface ModelProps extends GroupProps {}

export const Model = (
  {
    ref,
    ...props
  }: ModelProps & {
    ref: React.RefObject<THREE.Group>;
  }
) => {
  const { nodes, materials } = useGLTF("/WotW_title_3D-transformed.glb") as any;
  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh
        geometry={nodes.plane.geometry}
        material={materials["Material_0.002"]}
        position={[0, 1.945, 3.059]}
        rotation={[0, -1.519, 1.591]}
        scale={0.007}
      />
    </group>
  );
};
useGLTF.preload("/WotW_title_3D-transformed.glb");
export default Model;
