/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 404_broken_glass_separated.glb --transform 
Files: 404_broken_glass_separated.glb [60.48KB] > /Users/mehdi/Documents/dev/portfolio/public/404_broken_glass_separated-transformed.glb [8.46KB] (86%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/404_broken_glass_separated-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Curve.geometry} material={nodes.Curve.material} position={[0, -0.01, 0]} rotation={[Math.PI / 2, 0, -3.138]} scale={39.238} />
    </group>
  )
}

useGLTF.preload('/404_broken_glass_separated-transformed.glb')
