/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 404_broken_glass_separated.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/404_broken_glass_separated.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Curve.geometry} material={nodes.Curve.material} position={[0, -0.01, 0]} rotation={[Math.PI / 2, 0, -3.138]} scale={39.238} />
      <mesh geometry={nodes.Curve001.geometry} material={nodes.Curve001.material} position={[0, -0.01, 0]} rotation={[Math.PI / 2, 0, -3.138]} scale={39.238} />
      <mesh geometry={nodes.Curve002.geometry} material={nodes.Curve002.material} position={[0, -0.01, 0]} rotation={[Math.PI / 2, 0, -3.138]} scale={39.238} />
      <mesh geometry={nodes.Curve003.geometry} material={nodes.Curve003.material} position={[0, -0.01, 0]} rotation={[Math.PI / 2, 0, -3.138]} scale={39.238} />
      <mesh geometry={nodes.Curve004.geometry} material={nodes.Curve004.material} position={[0, -0.01, 0]} rotation={[Math.PI / 2, 0, -3.138]} scale={39.238} />
      <mesh geometry={nodes.Curve005.geometry} material={nodes.Curve005.material} position={[0, -0.01, 0]} rotation={[Math.PI / 2, 0, -3.138]} scale={39.238} />
      <mesh geometry={nodes.Curve006.geometry} material={nodes.Curve006.material} position={[0, -0.01, 0]} rotation={[Math.PI / 2, 0, -3.138]} scale={39.238} />
      <mesh geometry={nodes.Curve007.geometry} material={nodes.Curve007.material} position={[0, -0.01, 0]} rotation={[Math.PI / 2, 0, -3.138]} scale={39.238} />
      <mesh geometry={nodes.Curve008.geometry} material={nodes.Curve008.material} position={[0, -0.01, 0]} rotation={[Math.PI / 2, 0, -3.138]} scale={39.238} />
      <mesh geometry={nodes.Curve009.geometry} material={nodes.Curve009.material} position={[0, -0.01, 0]} rotation={[Math.PI / 2, 0, -3.138]} scale={39.238} />
      <mesh geometry={nodes.Curve010.geometry} material={nodes.Curve010.material} position={[0, -0.01, 0]} rotation={[Math.PI / 2, 0, -3.138]} scale={39.238} />
      <mesh geometry={nodes.Curve011.geometry} material={nodes.Curve011.material} position={[0, -0.01, 0]} rotation={[Math.PI / 2, 0, -3.138]} scale={39.238} />
      <mesh geometry={nodes.Curve012.geometry} material={nodes.Curve012.material} position={[0, -0.01, 0]} rotation={[Math.PI / 2, 0, -3.138]} scale={39.238} />
      <mesh geometry={nodes.Curve013.geometry} material={nodes.Curve013.material} position={[0, -0.01, 0]} rotation={[Math.PI / 2, 0, -3.138]} scale={39.238} />
      <mesh geometry={nodes.Curve014.geometry} material={nodes.Curve014.material} position={[0, -0.01, 0]} rotation={[Math.PI / 2, 0, -3.138]} scale={39.238} />
      <mesh geometry={nodes.Curve015.geometry} material={nodes.Curve015.material} position={[0, -0.01, 0]} rotation={[Math.PI / 2, 0, -3.138]} scale={39.238} />
      <mesh geometry={nodes.Curve016.geometry} material={nodes.Curve016.material} position={[0, -0.01, 0]} rotation={[Math.PI / 2, 0, -3.138]} scale={39.238} />
    </group>
  )
}

useGLTF.preload('/404_broken_glass_separated.glb')
