/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 404_broken_glass1.glb --transform 
Files: 404_broken_glass1.glb [48.14KB] > D:\Dokumente\dev\portfolio\portfolio\public\404_broken_glass1-transformed.glb [8.47KB] (82%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/404_broken_glass1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Curve.geometry} material={nodes.Curve.material} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={17.77} />
    </group>
  )
}

useGLTF.preload('/404_broken_glass1-transformed.glb')
