/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 404_broken_glass.glb --transform 
Files: 404_broken_glass.glb [48.1KB] > D:\Dokumente\dev\portfolio\portfolio\public\404_broken_glass-transformed.glb [8.44KB] (82%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/404_broken_glass-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Curve.geometry}
        material={nodes.Curve.material}
        rotation={[0, 0, -Math.PI]}
        scale={17.77}
      />
    </group>
  );
}

useGLTF.preload("/404_broken_glass-transformed.glb");
