/* eslint-disable react/display-name */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 LegacyLines1.glb 
*/
import React from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

type GroupProps = React.ComponentProps<"group">;
interface ModelProps extends GroupProps {}

// Forward ref for the Model component
// eslint-disable-next-line react/display-name

export const LegacyLines = ({
  ref,
  ...props
}: ModelProps & {
  ref: React.RefObject<THREE.Group>;
}) => {
  const { nodes, materials } = useGLTF("/LegacyLines1.glb") as any;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Curve.geometry}
        material={materials["SVGMat.056"]}
        position={[0, 0.022, -0.04]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Curve002.geometry}
        material={materials["SVGMat.058"]}
        position={[-0.002, 0.035, -0.036]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Curve003.geometry}
        material={materials["SVGMat.059"]}
        position={[0.01, 0.031, -0.036]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Curve004.geometry}
        material={materials["SVGMat.060"]}
        position={[0.007, 0.038, -0.036]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Curve005.geometry}
        material={materials["SVGMat.061"]}
        position={[-0.002, 0.03, -0.036]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Curve006.geometry}
        material={materials["SVGMat.062"]}
        position={[0.003, 0.026, -0.036]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Curve007.geometry}
        material={materials["SVGMat.063"]}
        position={[0.004, 0.037, -0.039]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Curve008.geometry}
        material={materials["SVGMat.064"]}
        position={[0.002, 0.035, -0.039]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Curve009.geometry}
        material={materials["SVGMat.065"]}
        position={[-0.005, 0.032, -0.036]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Curve010.geometry}
        material={materials["SVGMat.066"]}
        position={[0, 0.028, -0.036]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Curve011.geometry}
        material={materials["SVGMat.067"]}
        position={[0.01, 0.036, -0.036]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Curve012.geometry}
        material={materials["SVGMat.068"]}
        position={[0.004, 0.032, -0.032]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Curve013.geometry}
        material={materials["SVGMat.069"]}
        position={[0.007, 0.026, -0.036]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
};

/* useGLTF.preload("/LegacyLines1.glb"); */
