/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 LegacyLines1.glb --transform 
Files: LegacyLines1.glb [888.59KB] > C:\Users\mehdi\Documents\Uni\Bachelor\my-portfolio-proj\public\LegacyLines1-transformed.glb [79.77KB] (91%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/LegacyLines1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[1.554, -0.102, 3.114]} scale={105.456}>
        <mesh geometry={nodes.Curve131.geometry} material={materials['SVGMat.056']} />
        <mesh geometry={nodes.Curve131_1.geometry} material={materials['SVGMat.058']} />
        <mesh geometry={nodes.Curve131_2.geometry} material={materials['SVGMat.068']} />
      </group>
    </group>
  )
}

useGLTF.preload('/LegacyLines1-transformed.glb')
