/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 LegacyLines.glb --transform 
Files: LegacyLines.glb [461.63KB] > D:\Dokumente\Mehdi Studium Informatik und Design\7. Semester\Bachelor\my-portfolio-proj\public\LegacyLines-transformed.glb [48.14KB] (90%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

type GroupProps = React.ComponentProps<"group">;

interface ModelProps extends GroupProps {}

// Forward ref for the Model component
// eslint-disable-next-line react/display-name
export const LegacyLines = ({
  ref,
  ...props
}: ModelProps & {
  ref: React.RefObject<THREE.Group>;
}) => {
  const { nodes, materials } = useGLTF("/LegacyLines1-transformed.glb") as any;
  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh
        geometry={nodes.Curve.geometry}
        material={materials["SVGMat.056"]}
      />
      <mesh
        geometry={nodes.Curve002.geometry}
        material={materials["SVGMat.058"]}
        position={[0, 0.004, 0]}
      />
      <mesh
        geometry={nodes.Curve012.geometry}
        material={materials["SVGMat.068"]}
        position={[0, 0.007, 0]}
      />
    </group>
  );
};
