/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 WotW_title_3D.gltf 
*/

import React, { forwardRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

type GroupProps = JSX.IntrinsicElements["group"];
interface ModelProps extends GroupProps {}

// eslint-disable-next-line react/display-name
export const WotwTitle = forwardRef<THREE.Group, ModelProps>((props, ref) => {
  const { nodes, materials } = useGLTF("/WotW_title_3D-transformed") as any;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.plane.geometry}
        material={nodes.plane.material}
        material-depthWrite={true}
      />
      <mesh
        geometry={nodes.plane_1.geometry}
        material={nodes.plane_1.material}
        position={[0, 215, 0]}
        material-depthWrite={true}
      />
      <mesh
        geometry={nodes.plane_2.geometry}
        material={nodes.plane_2.material}
        position={[0, 444, 0]}
        material-depthWrite={true}
      />
      <mesh
        geometry={nodes.plane_3.geometry}
        material={nodes.plane_3.material}
        position={[-14, 693, -206]}
        material-depthWrite={true}
      />
      <mesh
        geometry={nodes.plane_4.geometry}
        material={nodes.plane_4.material}
        position={[0, 887, 0]}
        material-depthWrite={true}
      />
    </group>
  );
});

useGLTF.preload("/WotW_title_3D.gltf");
