/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 WotW.glb 
*/

import React, { forwardRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

type GroupProps = JSX.IntrinsicElements["group"];
interface ModelProps extends GroupProps {}

// eslint-disable-next-line react/display-name
export const WotwTitle = forwardRef<THREE.Group, ModelProps>((props, ref) => {
  const { nodes, materials } = useGLTF("/WotW.glb") as any;
  return (
    <group ref={ref} {...props} dispose={null}>
      <group
        position={[0, 1.945, 3.059]}
        rotation={[0, -1.519, 1.591]}
        scale={0.007}
      >
        <mesh
          geometry={nodes.plane.geometry}
          material={materials["Material_0.002"]}
        />
        <mesh
          geometry={nodes.plane001.geometry}
          material={materials["Material_0.002"]}
          position={[0, 215, 0]}
        />
        <mesh
          geometry={nodes.plane002.geometry}
          material={materials["Material_0.002"]}
          position={[0, 444, 0]}
        />
        <mesh
          geometry={nodes.plane003.geometry}
          material={materials["Material_0.002"]}
          position={[2.816, 691.035, -237.074]}
        />
        <mesh
          geometry={nodes.plane004.geometry}
          material={materials["Material_0.002"]}
          position={[0, 887, 0]}
        />
      </group>
    </group>
  );
});

useGLTF.preload("/WotW.glb");
