import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/app/utils/providers";
import { Heebo } from "next/font/google";
import { IBM_Plex_Sans } from "next/font/google";
import { Ubuntu } from "next/font/google";
import localFont from "next/font/local";

const inter = Inter({ subsets: ["latin"] });

const heebo = Heebo({ subsets: ["latin"], variable: "--font-heebo" });
const iBMPlexSans = IBM_Plex_Sans({
  weight: "600",
  subsets: ["latin"],
  variable: "--font-iBMPlexSans",
});
const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: "500",
  variable: "--font-ubuntu",
});

const pPMonumentExtendedBlack = localFont({
  src: "./fonts/PPMonumentExtendedBlack.woff",
  variable: "--font-pPMonumentExtended-Black",
});

export const metadata: Metadata = {
  title: "Portfolio Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pPMonumentExtendedBlack.variable} ${ubuntu.variable} ${heebo.variable} ${iBMPlexSans.variable} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
