/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 butterfly.glb --transform 
Files: butterfly.glb [3.05MB] > C:\Users\mehdi\Documents\Uni\Bachelor\my-portfolio-proj\public\3D models\butterfly-transformed.glb [138.52KB] (95%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/butterfly-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Curve033_2.geometry} material={materials['SVGMat.032']} />
        <mesh geometry={nodes.Curve033_3.geometry} material={materials['SVGMat.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/butterfly-transformed.glb')
